channel: stable-4.12
version: 4.12.20
subscriptions:
  - name: kiali-ossm
    namespace: openshift-operators
    channel: stable
    source: redhat-operators
  - name: servicemeshoperator
    namespace: openshift-operators
    channel: stable
    source: redhat-operators
  - name: amq-streams
    namespace: openshift-operators
    channel: stable
    source: redhat-operators
  - name: patch-operator
    namespace: patch-operator
    channel: alpha
    source: community-operators
  - name: serverless-operator
    namespace: openshift-serverless
    channel: stable
    source: redhat-operators
acs:
  enabled: false
sealedsecrets:
  enabled: false
gitops:
  enabled: false
knative:
  enabled: true
kafka:
  enabled: true
  dedicatedNode: false