broker:
  topicsAutoCreation: false
  nodes: 3
  metricsEnabled: true
  volumeSize: 50Gi
  replication: 3
  minInSync: 2

topics:
  - name: test-1
  - name: test-2
  - name: test-3
    retention: 360000