apiVersion: v1
kind: ResourceQuota
metadata:
  name: pminkows-prod-quota
  namespace: pminkows-prod
spec:
  hard:
    pods: '8'
    requests.cpu: '2'
    requests.memory: 4Gi
    limits.cpu: '8'
    limits.memory: 10Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pminkows-stage-quota
  namespace: pminkows-stage
spec:
  hard:
    pods: '5'
    requests.cpu: '2'
    requests.memory: 2Gi
    limits.cpu: '8'
    limits.memory: 8Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pminkows-test-quota
  namespace: pminkows-test
spec:
  hard:
    pods: '5'
    requests.cpu: '2'
    requests.memory: 2Gi
    limits.cpu: '8'
    limits.memory: 8Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pminkows-cicd-quota
  namespace: pminkows-cicd
spec:
  hard:
    pods: '15'
    requests.cpu: '5'
    requests.memory: 4Gi
    limits.cpu: '10'
    limits.memory: 12Gi