clusterName: gcp-1
baseDomain: openshiftcorp.dev
region: europe-west1
project: openshift-366120
provider: Google
workerType: n1-standard-4
workerReplicas: 3
managedSet: all-demo
version: 4.10.47
autoscaling: false