apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: global-config
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/piomin/openshift-cluster-config.git
        revision: HEAD
        directories:
          - path: applicationset/projects/*
  template:
    metadata:
      name: '{{.path.basename}}-config-{{name}}'
    spec:
      destination:
        namespace: '{{.path.basename}}'
        server: '{{server}}'
      project: default
      sources:
        - path: applicationset/chart
          repoURL: 'https://github.com/piomin/openshift-cluster-config.git'
          targetRevision: HEAD
          helm:
            valueFiles:
              - $values/applicationset/projects/{{.path.basename}}/values.yaml
            parameters:
              - name: projectName
                value: '{{.path.basename}}'
              - name: argoNamespace
                value: openshift-gitops
        - repoURL: 'https://github.com/piomin/openshift-cluster-config.git'
          targetRevision: HEAD
          ref: values
      syncPolicy:
        automated:
          prune: true
          selfHeal: true